
# kubectl label nodes <node-name> intensive=general
# kubectl label nodes <node-name> intensive=memory
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx1
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive : general
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive : memory
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx2
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive : does-not-exist
---
