
# kubectl label nodes <node-name> intensive=general
# kubectl label nodes <node-name> intensive=memory
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive: general
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx1
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive: general
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx2
spec:
   containers:
      - name: nginx
        image: nginx
   nodeSelector:
      intensive: memory
---

#6  05/02/24 14:53:54 aws eks update-kubeconfig --name demo --region us-east-1
#7  05/02/24 14:54:27 cp /home/centos/.kube/config /tmp/kubeconfig
#8  05/02/24 14:54:44 kubectl --kubeconfig=/tmp/kubeconfig
#9  05/02/24 14:54:51 kubectl --kubeconfig=/tmp/kubeconfig get all
