apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: intensive
                      operator: NotIn #
                      values:
                         - general
   containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   affinity:
      nodeAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: intensive
                      operator: NotIn #
                      values:
                         - memory
                         - general
   containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---