---
apiVersion: v1
kind: Pod
metadata:
   name: nginx1
spec:
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: intensive
                      operator: In
                      values:
                         - general
   containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx2
spec:
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                    - key: intensive
                      operator: In
                      values:
                         - doesnot-exist
   containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx3
spec:
   affinity:
      nodeAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                 matchExpressions:
                    - key: intensive
                      operator: In
                      values:
                         - doesnot-exist
   containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---