---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: frontend
   labels:
      app: guestbook
      tier: frontend
spec:
   # modify replicas according to your case
   replicas: 3
   selector:
      matchLabels:
         tier: frontend
   template:
      metadata:
         labels:
            tier: frontend
      spec:
         containers:
            - name: php-redis
              image: nginx
---
apiVersion: v1
kind: Pod
metadata:
   name: nginx
   labels:
      env: test
spec:
   nodeSelector:
      intensive: memory
   containers:
      -  name: nginx
         image: nginx
         imagePullPolicy: IfNotPresent
   tolerations:
      -  key: "special"
         operator: "Exists"
         effect: "NoSchedule"
---