---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: admin-role-to-sample-sa
subjects:
   - kind: ServiceAccount
     name:  admin-sa
     namespace: default
roleRef:
   kind: ClusterRole
   name: admin
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
   name: sample-sa
spec:
   ServiceAccount: "admin-sa"
   containers:
      - name: centos
        image: centos:8
        command:
           - sleep
           - "10000"
---