apiVersion: v1
kind: Pod
metadata:
   name: pod03
spec:
   containers:
      - name: nginx
        image: nginx
      - name: ping
        image: rkalluru/ping:v1
        args:
           - yahoo.com

