---
apiVersion: v1
kind: ResourceQuota
metadata:
   name: mem-cpu-quota
   namespace: default
spec:
   hard:
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
   name: frontend
spec:
   containers:
      - name: app
        image: nginx
        resources:
           requests:
              memory: "600Mi"
              cpu: "400m"
           limits:
              memory: "800Mi"
              cpu: "600m"
---
apiVersion: v1
kind: Pod
metadata:
   name: frontend-demo
spec:
   containers:
      - name: app1
        image: nginx
        resources:
           requests:
              memory: "600Mi"
              cpu: "400m"
           limits:
              memory: "800Mi"
              cpu: "600m"
---