---
#apiVersion: v1
#kind: Pod
#metadata:
#   name: pod01
#spec:
#   containers:
#      - name: httpd
#        image: rkalluru/k06-configmap:v1
#        env:
#           -  name: APP_NAME
#              value: demo
#           -  name: PROJECT_NAME
#              value: demo
#           -  name: ENVIRONMENT
#              value: dev
#           -  name: CLOUD
#              value: aws
#           -  name: REGION
#              value: "us-east-1"
#           -  name: IS_VPC
#              value: "true"
#           -  name: COMPONENT
#              value: httpd
#           -  name: SOFTWARE
#              value: apache
#           -  name: SOFTWARE_VERSION
#              value: "2.1"
#           -  name: APP_VERSION
#              value: "1.0.0"

---
apiVersion: v1
kind: ConfigMap
metadata:
   name: proj-info
data:
   APP_NAME: demo
   PROJECT_NAME: demo
   ENVIRONMENT: dev
   CLOUD: aws
   REGION: "us-east-1"
   IS_VPC: "true"
   COMPONENT: httpd
   SOFTWARE: apache
   SOFTWARE_VERSION: "2.1.1"
   APP_VERSION: "1.0.0"
---
apiVersion: v1
kind: Pod
metadata:
   name: pod01
spec:
   containers:
      - name: httpd
        image: rkalluru/k06-configmap:v1
        env:
           -   name: APP_NAME
               valueFrom:
                  configMapKeyRef:
                     key: APP_NAME
                     name: proj-info
           -  name: PROJECT_NAME
              valueFrom:
                 configMapKeyRef:
                    key: PROJECT_NAME
                    name: proj-info
           -  name: ENVIRONMENT
              valueFrom:
                  configMapKeyRef:
                     key: ENVIRONMENT
                     name: proj-info
           -  name: CLOUD
              valueFrom:
                 configMapKeyRef:
                    key: CLOUD
                    name: proj-info
           -  name: REGION
              valueFrom:
                 configMapKeyRef:
                    key: REGION
                    name: proj-info
           -  name: IS_VPC
              valueFrom:
                 configMapKeyRef:
                    key: IS_VPC
                    name: proj-info
           -  name: COMPONENT
              valueFrom:
                 configMapKeyRef:
                    key: COMPONENT
                    name: proj-info
           -  name: SOFTWARE
              valueFrom:
                 configMapKeyRef:
                    key: SOFTWARE
                    name: proj-info
           -  name: SOFTWARE_VERSION
              valueFrom:
                 configMapKeyRef:
                    key: SOFTWARE_VERSION
                    name: proj-info
           -  name: APP_VERSION
              valueFrom:
                 configMapKeyRef:
                    key: APP_VERSION
                    name: proj-info

---
