apiVersion: v1
kind: ConfigMap
metadata:
   name: nginx-conf
data:
   nginx.conf: |
      server {
      listen       80;
      server_name  localhost;
      
      #access_log  /var/log/nginx/host.access.log  main;
      
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
      
      #error_page  404              /404.html;
      
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
      
      proxy_http_version 1.1;
      location /images/ {
      expires 5s;
      root   /usr/share/nginx/html;
      try_files $uri /images/placeholder.jpg;
      }
      location /api/catalogue/ { proxy_pass http://catalogue:8080/; }
      location /api/user/ { proxy_pass http://user:8080/; }
      location /api/cart/ { proxy_pass http://cart:8080/; }
      location /api/shipping/ { proxy_pass http://shipping:8080/; }
      location /api/payment/ { proxy_pass http://payment:8080/; }
      
      location /health {
      stub_status on;
      access_log off;
      }
      # proxy the PHP scripts to Apache listening on 127.0.0.1:80
      #
      #location ~ \.php$ {
      #    proxy_pass   http://127.0.0.1;
      #}
      
      # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
      #
      #location ~ \.php$ {
      #    root           html;
      #    fastcgi_pass   127.0.0.1:9000;
      #    fastcgi_index  index.php;
      #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
      #    include        fastcgi_params;
      #}
      
      # deny access to .htaccess files, if Apache's document root
      # concurs with nginx's one
      #
      #location ~ /\.ht {
      #    deny  all;
      #}
      }
---
apiVersion: v1
kind: Pod
metadata:
   name: pod-file-test
spec:
   containers:
      - name: frontend
        image: hemanthtadikonda/frontend:2.6.0
        volumeMounts:
           -  name: config-volume
              mountPath: /data
   volumes:
      -  name: config-volume
         configMap:
            name: nginx-conf