---
apiVersion: v1
kind: Secret
metadata:
   name: my-secrets
data:
   DB_PASSWORD: YWJjZDEyMzQ=
   APP_PASSWORD: cm9vdDU2Nzg=
---
apiVersion: v1
kind: Pod
metadata:
   name: secretpod01
spec:
   containers:
      - name: centos
        image: centos:7
        command: ["sleep","3600"]
        env:
           -  name: db_password
              valueFrom:
                 secretKeyRef:
                    key: DB_PASSWORD
                    name: my-secrets
---
apiVersion: v1
kind: Pod
metadata:
   name: secretpod02
spec:
   containers:
      - name: centos
        image: centos:7
        command: ["sleep","3600"]
        envFrom:
           -  secretRef:
                 name: my-secrets


