apiVersion: v1
kind: Pod
metadata:
   name: ebs
spec:
   containers:
      - image: centos:8
        name: centos
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: /test-ebs
             name: test-volume
   volumes:
      - name: test-volume
         # This Portworx volume must already exist.
        portworxVolume:
           volumeID: "vol-02c72c6dae48e2357"
           fsType: "ext4"