apiVersion: v1
kind: Pod
metadata:
   name: test-pod
spec:
   containers:
      - image: centos:8
        name: centos
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: /cache
             name: cache-volume
   volumes:
      - name: cache-volume
        emptyDir:
           sizeLimit: 500Mi