---
apiVersion: v1
kind: Pod
metadata:
   name: hostpath-pod
spec:
   containers:
      - name: centos
        image: centos:7
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: /cache
             name: test-volume
   volumes:
      - name: test-volume
         # mount /data, but only if that directory already exists
        hostPath:
           path: /home/centos/data  # directory location on host
           type: Directory # this field is optional