---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: my-sc

parameters:
   csi.storage.k8s.io/fstype: xfs
   encrypted: "true"
   type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: claim1
spec:
   accessModes:
      - ReadWriteOnce
   volumeMode: Block
   resources:
      requests:
         storage: 1Gi
   storageClassName: "aws-st1"
---
apiVersion: v1
kind: Pod
metadata:
   name: pod-sc
spec:
   containers:
      - image: centos:8
        name: centos
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: /data
             name: data
   volumes:
      - name: data
        persistentVolumeClaim:
           claimName: claim1