---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: gp3-retain
parameters:
   csi.storage.k8s.io/fstype: xfs
   encrypted: "true"
   type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: claim2
spec:
   accessModes:
      - ReadWriteOnce
   volumeMode: Block
   resources:
      requests:
         storage: 1Gi
   storageClassName: "gp3-retain"
---
apiVersion: v1
kind: Pod
metadata:
   name: pod-sc
spec:
   containers:
      - image: centos:8
        name: centos
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: "/opt"
             name: claim2
   volumes:
      - name: claim2
        persistentVolumeClaim:
           claimName: claim2