---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: claim1
spec:
   accessModes:
      - ReadWriteOnce
   volumeMode: Block
   resources:
      requests:
         storage: 1Gi
   storageClassName: aws-gp3
---
apiVersion: v1
kind: Pod
metadata:
   name: pod-sc
spec:
   containers:
      - image: centos:8
        name: centos
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           - mountPath: /data
             name: data
   volumes:
      - name: data
        persistentVolumeClaim:
           claimName: claim1

