apiVersion: v1
kind: Pod
metadata:
   name: pod03
spec:
   containers:
      - name: nginx
        image: nginx
      - name: ping
        image: hemanthtadikonda/ping:v1
        command: ["echo"]
        args:
           - hemanth.com


## command is to override CMD  in an image
# arg:to pass arguements to ENTRYPOINT of an image