apiVersion: v1
kind: Pod
metadata:
   name: pod03
spec:
   containers:
      - name: nginx
        image: nginx
      - name: ping
        image: rkalluru/ping:v1
        command: ["ping","-c30"]
        args:
           - yahoo.com

## command is to override CMD  in an image
# arg:to pass arguements to ENTRYPOINT of an image