---
apiVersion: v1
kind: Pod
metadata:
   name: port01
spec:
   containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Pod
metadata:
   name: port02
spec:
   containers:
      - name: nginx
        image: nginx
      -  name: centos
         image: centos:7
         command:
            -  sleep
            -  "10000"
---
##YAML: can supports to write multiple yaml files in single file by delimiting with {---}

