---
apiVersion: v1
kind: Pod
metadata:
   name: resources01
spec:
   containers:
      - name: nginx
        image: nginx
        resources:
           requests:
              memory: "64Mi"
              cpu: "150m"
           limits:
              memory: "128Mi"
              cpu: "300m"
---

apiVersion: v1
kind: Pod
metadata:
   name: resources02
spec:
   containers:
      - name: centos
        image: centos:8
        command:
           -  sleep
           -  "10000"
        resources:
           limits:
              memory: "128Mi"
              cpu: "500m"
           requests:
              memory: "72Mi"
              cpu: "100m"

---

### resources: can be applied in container level
# Requests: the min amount of resources will take to create a container
# Limits: the maximum amount of resources can be used by container

