---
apiVersion: v1
kind: Pod
metadata:
   labels:
      test: liveness
   name: liveness-exec
spec:
   containers:
      - name: liveness
        image: registry.k8s.io/busybox
        args:
           - /bin/sh
           - -c
           - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
           exec:
              command:
                 - cat
                 - /tmp/healthy
           initialDelaySeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
   labels:
      test: liveness
   name: liveness-test-pod
spec:
   containers:
      - name: liveness
        image: rkalluru/liveness:v1
        ports:
        -  containerPort: 80
        livenessProbe:
           httpGet:
              path: /
              port: 80
           initialDelaySeconds: 5
           periodSeconds: 5
---