apiVersion: v1
kind: Pod
metadata:
   name: pod02
spec:
   securityContext:
      runAsNonRoot: true
   containers:
      - name: centos
        image: rkalluru/k06-nonroot
        volumeMounts:
           -  mountPath: /data
              name: root-volume
   volumes:
      -  name: root-volume
         hostPath:
            path: /
            type: Directory
