apiVersion: v1
kind: Pod
metadata:
   name: pod00
spec:
   securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
   containers:
      - name: centos
        image: centos:7
        command:
           -   sleep
           -   "10000"
        volumeMounts:
           -  mountPath: /data
              name: root-volume
   volumes:
      -  name: root-volume
         hostPath:
            path: /
            type: Directory
